<a href="https://colab.research.google.com/github/AlexTapioka/simulative-git/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [186]:
import numpy as np

#Numpy. Урок 1

##Одномерные массивы


Подключение библиотеки

In [169]:
import numpy as np

Создать одномерный массив

In [170]:
a = np.array([1, 2, 3, 4, 5])


Тип массива

In [171]:
type(a)

numpy.ndarray

Число элеменов массива

In [172]:
a.shape

(5,)

Размерность массива

In [173]:
a.ndim

1

Тип элементов массива

In [174]:
a.dtype

dtype('int64')

Установить тип данных при создании массива

In [175]:
arr = [1,2,3,4,5,6,7,8,9,10]
a = np.array(arr, dtype=np.float64)
a.dtype

dtype('float64')

Изменить тип данных в массиве

In [176]:
a.astype(np.int32)
a.dtype

dtype('float64')

Другой способ создать массив

In [177]:
aff = [1,2,3,4,5,6,7,8,9]
b = np.asarray(arr)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###Математичесике операции:


---



Над массивами можно осуществлять различные математические операции( сложение по элементам, вычитание, умножение)

In [178]:
a+b

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [179]:
a-b


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [180]:
a*b

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

Деление одного массива на другой

In [181]:
np.divide(a,b)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

###Аггрегирующие функции:

---



Сумма массива

In [182]:
a.sum()

55.0

Среднее значение массива

In [183]:
a.mean()

5.5

Минимум, максимум

In [184]:
a.min()

1.0

In [185]:
a.max()

10.0

##Многомерные массивы

---



Создание массива

In [18]:
arr2 = [1,2,4,5,6],[1,3,4,5,6]
b = np.array(arr2)
b

array([[1, 2, 4, 5, 6],
       [1, 3, 4, 5, 6]])

Размерность массива (кол - во строк, кол-во столбцов)

In [19]:
b.shape

(2, 5)

Количество размерностей

In [20]:
b.ndim

2

###Математические операции

Сложение (поэлементное сложение)

In [21]:
c = np.array(arr2)
b + c

array([[ 2,  4,  8, 10, 12],
       [ 2,  6,  8, 10, 12]])

###Аггрерирующие функции


Можно применять по размерностям:

axis = 0 (кол-во матриц, из которых состоит массив)

axis = 1 (кол-во строк в каждой матрице)

axis = 2 (кол-во столбцов в каждой матрице)

In [22]:
arr3 = [
    [
    [1, 2, 3, 4, 5, 6],
    [90, 2, 3, 4, 5, 6]
    ],
    [
    [1, 2, 3, 4, 5, 6],
    [9, 2, 3, 4, 5, 6]
    ],
    [
    [1, 2, 3, 4, 5, 6],
    [113, 2, 3, 4, 5, 6]
    ]
    ]
c = np.array(arr3, dtype = np.int32)


In [23]:
c.shape

(3, 2, 6)

In [24]:
c.sum(axis = 0)

array([[  3,   6,   9,  12,  15,  18],
       [212,   6,   9,  12,  15,  18]])

In [25]:
c.sum(axis = 1)

array([[ 91,   4,   6,   8,  10,  12],
       [ 10,   4,   6,   8,  10,  12],
       [114,   4,   6,   8,  10,  12]])

In [26]:
c.sum(axis = 2)

array([[ 21, 110],
       [ 21,  29],
       [ 21, 133]])

In [27]:
c.sum( axis=(0, 1) ) # Сумма всех строк во всех матрицах

array([215,  12,  18,  24,  30,  36])

##Создание матриц


Создать единичную матрицу (с единицами в главной диагонали)

In [28]:
np.eye(5,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

Создать нулевую матрицу (заполненную нулями)

In [29]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [30]:
a = np.empty((2,3,5)) # тоже создает пустую матрицу, но с непредсказуемыми значениями


Создает матрицу, заполненную конкретными значениями

In [31]:
np.full((2,3,5), fill_value=15)

array([[[15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15]],

       [[15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15]]])

Создает матрицу, заполненную единицами

In [32]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

Создать матрицу на основе другой, но заполненную единицами

In [33]:
np.ones_like(a)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# Полезные функции

Создать диапазон с дробным шагом


In [34]:
np.arange(0,10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

Создать диапазон с подогнанным под нужное кол-во элементов шагом

In [35]:
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

##Срезы матриц


Правая граница не входит в диапазон


In [36]:
c.shape

(3, 2, 6)

In [37]:
c[1:, :1, 2: ]

array([[[3, 4, 5, 6]],

       [[3, 4, 5, 6]]], dtype=int32)

In [38]:
a = c[0,1]
a

array([90,  2,  3,  4,  5,  6], dtype=int32)

Массив в обратном порядке

In [39]:
a[::-1]

array([ 6,  5,  4,  3,  2, 90], dtype=int32)

Выборка конкретных значений из массива

In [40]:
a[1:4:2] #Каждый второй элемент

array([2, 4], dtype=int32)

Заменить элементы

In [41]:
a[1:4:2] = 100
a

array([ 90, 100,   3, 100,   5,   6], dtype=int32)

Если создаем копию на основе массива, нужно использовать метод copy(). Тогда элементы в исходном массиве не будут изменяться

In [42]:
b = a
b[::3] = 1000
b

array([1000,  100,    3, 1000,    5,    6], dtype=int32)

In [43]:
c = a.copy()
print(c, a)
c[1] = 10000
print(c, a)

[1000  100    3 1000    5    6] [1000  100    3 1000    5    6]
[ 1000 10000     3  1000     5     6] [1000  100    3 1000    5    6]


# Numpy Урок 2


##Броадкастинг

In [66]:
x = np.array([1,2,3,])
a = 5

In [67]:
x * a # (a преобразовывается в массив)

array([ 5, 10, 15])

In [68]:
x = np.ones((2,3,5,1))
y = np.ones((2,1,5,8))

c = x * y #берет большую размерность

c.shape

(2, 3, 5, 8)

In [69]:
x = np.ones((3,5,1))
y = np.ones((2,1,5,8))

z =x * y #Добавляет измерение, если матрицы разной размерности.
          #Если они приводимы.
z.shape

(2, 3, 5, 8)

In [70]:
a = np.ones((3,5,4,1))
a.shape, a.ndim

((3, 5, 4, 1), 4)

Переделать исходный массив в ту форму, которую мы указываем.
Не меняет кол-во данных!!!

In [71]:
a.reshape((3,5,2,2))
a.shape

(3, 5, 4, 1)

Переделать исходный массив в ту форму, которую мы указываем. Меняет кол-во данных

In [72]:
np.resize(a, (3,5,4,2)) #не меняет исходный массив
                        # недостающие данные заполняются копией данных из исходного массива

a.shape

(3, 5, 4, 1)

In [73]:
b = np.ones((3,5,4,1)) # Меняет исходный массив.
                      # Недостающие данные заполняются 0
b.resize((3,5,4,2))
b.shape

(3, 5, 4, 2)

Расширить массив измерениями с единицами

In [74]:
a = np.ones((2, 255, 255))
b = np.expand_dims(a, axis = (0,2,4)) #в скобках указать оси
b.shape

(1, 2, 1, 255, 1, 255)

Удалить измерения из массива

In [75]:
b.squeeze(axis =(0,2)).shape # по умолчанию удаляет оси с единицами

(2, 255, 1, 255)

Добавить значения по краям массива

In [76]:
np.pad(a, pad_width=(2,3), constant_values=1).shape

(7, 260, 260)

###Сделать массив плоским

Возвращает новый массив с плоской матрицей

In [77]:
b = np.zeros((2, 3, 5, 1))
c = np.ravel(b)
c.shape, b.shape

((30,), (2, 3, 5, 1))

In [78]:
b.flatten() # only as method. return a copy

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
b.reshape(-1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Переделать массив в список python

In [80]:
b.tolist()

[[[[0.0], [0.0], [0.0], [0.0], [0.0]],
  [[0.0], [0.0], [0.0], [0.0], [0.0]],
  [[0.0], [0.0], [0.0], [0.0], [0.0]]],
 [[[0.0], [0.0], [0.0], [0.0], [0.0]],
  [[0.0], [0.0], [0.0], [0.0], [0.0]],
  [[0.0], [0.0], [0.0], [0.0], [0.0]]]]

###Преобразование массивов

1.   Вставка
2.   Разбивка



Разбить массив на отдельные кусочки

In [81]:
a = np.arange(9)

np.split(a, [3,5,15]) # можно указать одно число или индексы или секции

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([], dtype=int64)]

In [82]:
a = np.array([[1,2,3],[1,2,3]])
a.shape

(2, 3)

In [83]:
np.split(a, 3, axis=1)

[array([[1],
        [1]]),
 array([[2],
        [2]]),
 array([[3],
        [3]])]

Вставка в массив

In [84]:
np.insert(a, (1,2), (1000,3000), axis=1)
#куда, на какое место, что вставить, ось

array([[   1, 1000,    2, 3000,    3],
       [   1, 1000,    2, 3000,    3]])

Добавление в конец

In [85]:
np.append(a, values=[[100, 200, 300], [100, 200, 300]], axis =1)
# обязательно соблюдать внешнюю размерность(та, которая не в axis)

array([[  1,   2,   3, 100, 200, 300],
       [  1,   2,   3, 100, 200, 300]])

  ### Поиск уникальных значений в массиве

In [88]:
a = np.array([[1,2,3],[4,5,6]])
a =np.append(a, [[1,2,3]], axis = 0)


In [89]:
a = np.append(a, [[1],[1],[1]], axis = 1)


Сделает массив плоским и оставит уникальные элементы

In [90]:
np.unique(a)

array([1, 2, 3, 4, 5, 6])

Выводит уникальные массивы

In [91]:
np.unique(a, axis=0)

array([[1, 2, 3, 1],
       [4, 5, 6, 1]])

возвращает индексы первого вхождения уникальных значений

In [95]:
els, inxs = np.unique(a, axis=0, return_index=True)
inxs

array([0, 1])

вывести все вхождения уникальных индексов в массив

In [97]:
els, inxs = np.unique(a, axis=0, return_inverse=True)
inxs

array([0, 1, 0])

Это позволит сконструировать исходный массив

In [98]:
els[inxs]

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

Сколько каждый элемент массива повторился

In [100]:
els, cnt = np.unique(a, axis=0, return_counts=True)
cnt

array([2, 1])

###Дублировать массив(значения)

Повторить каждую строку массива, указанное кол-во раз

In [103]:
a

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [102]:
np.tile(a, 2)

array([[1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1]])

Повторение строк, но в другом измерении **подряд**

In [104]:
np.tile(a, (2,1))

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1],
       [1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

Плоский массив, в котором значения продублированы указанное кол-во раз

In [105]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 1, 1, 4, 4, 5, 5, 6, 6, 1, 1, 1, 1, 2, 2, 3, 3,
       1, 1])

если указываем ось, просто повторяет ее ее **последовательно**

In [106]:
np.repeat(a, 2, axis=0)

array([[1, 2, 3, 1],
       [1, 2, 3, 1],
       [4, 5, 6, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1],
       [1, 2, 3, 1]])

###Конкантенация и обьединение массивов

Обьединить два массива, по совпадающей размерности.

In [113]:
a

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [111]:

b = np.repeat(a, 3, axis=1)
b

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [4, 4, 4, 5, 5, 5, 6, 6, 6, 1, 1, 1],
       [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

In [112]:
np.concatenate((a,b), axis =1)

array([[1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [4, 5, 6, 1, 4, 4, 4, 5, 5, 5, 6, 6, 6, 1, 1, 1],
       [1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

Если размерности совпадают, можно не указывать ось

In [116]:
c = a.copy()
np.concatenate((a,c*2)) #можно умножить значения или что-то другое

array([[ 1,  2,  3,  1],
       [ 4,  5,  6,  1],
       [ 1,  2,  3,  1],
       [ 2,  4,  6,  2],
       [ 8, 10, 12,  2],
       [ 2,  4,  6,  2]])

Горизонтальное соединение по столбцам (ставим одно на другое) или concantenate с axis = 2

In [117]:
np.hstack((a,b))

array([[1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [4, 5, 6, 1, 4, 4, 4, 5, 5, 5, 6, 6, 6, 1, 1, 1],
       [1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

Конкантенация по строкам или concantenate с axis = 0

In [118]:
np.vstack((a,b))

ValueError: ignored

#Полезные функции

Произведение всех элементов по заданному правилу

Произведение всех элементов массива

In [120]:
a.prod()

4320

Осторожно!!! Если массив пустой, получаем 1

In [121]:
np.array([]).prod()

1.0

Умножение по столбикам

In [125]:
a.prod(axis=0)

array([ 4, 20, 54,  1])

Умножение по строкам

In [124]:
a.prod(axis=1)

array([  6, 120,   6])

  Округлить каждый элемент массива до указанного знака после запятой

In [129]:
b = a*1.025467
b
b.round(2)

array([[1.03, 2.05, 3.08, 1.03],
       [4.1 , 5.13, 6.15, 1.03],
       [1.03, 2.05, 3.08, 1.03]])

### Сортировка

Сравает все значения между собой

In [132]:
np.sort(b)

array([[1.025467, 1.025467, 2.050934, 3.076401],
       [1.025467, 4.101868, 5.127335, 6.152802],
       [1.025467, 1.025467, 2.050934, 3.076401]])

Сравнивает массивы между собой

In [ ]:
np.sort(b, axis=0)

выводит индексы элементов ранжированные по значениям

In [133]:
np.argsort(b) #По умлочанию axis=1

array([[0, 3, 1, 2],
       [3, 0, 1, 2],
       [0, 3, 1, 2]])

In [134]:
np.argsort(b, axis=0)

array([[0, 0, 0, 0],
       [2, 2, 2, 1],
       [1, 1, 1, 2]])

Плоский массив

In [135]:
np.argsort(b, axis=None)

array([ 0,  3,  7,  8, 11,  1,  9,  2, 10,  4,  5,  6])

Найти индекс минимального элемента


In [139]:
np.argmin(b)

0

Найти индекс максимального элемента

In [140]:
np.argmax(a)

7

Извлечь диагональ из квадрата матриц (по умолчанию - главная (от верхнего левого элемента к правому нижнему))

In [144]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
np.diag(a)

array([0, 4, 8])

извлечь диагональ по значению k (если k > 0, то это диагональ над главной диагональю (справа),если  k < 0, то это диагональ под главной диагональю(слева))

In [150]:
np.diag(a, k=-2)

array([6])

## Фильтрация

Фильтраця по условию (Получаем 2 массива. 1-строки, 2-столбцы. это положение эл-тов которые удовлетворяют условию)

In [157]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [155]:
np.where(a<3)

(array([0, 0, 0]), array([0, 1, 2]))

In [156]:
np.where(a%2 ==1)

(array([0, 1, 1, 2]), array([1, 0, 2, 1]))

Вернуть результат со значениямы в одномерном массиве

In [158]:
a[np.where(a%2 ==1)]

array([1, 3, 5, 7])

Комбинирование условий

и

In [159]:
np.where((a%2 == 1)&(a > 3))

(array([1, 2]), array([2, 1]))

In [160]:
np.where(np.logical_and(a%2 == 1,a > 3 ))

(array([1, 2]), array([2, 1]))

или

In [162]:
np.where((a%2 == 1)|(a > 3))

(array([0, 1, 1, 1, 2, 2, 2]), array([1, 0, 1, 2, 0, 1, 2]))

In [161]:
np.where(np.logical_or(a%2 == 1,a > 3 ))

(array([0, 1, 1, 1, 2, 2, 2]), array([1, 0, 1, 2, 0, 1, 2]))

Можем менять значение отфильтрованных данных

In [163]:
np.where(a>5, a,-1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [ 6,  7,  8]])

In [168]:
np.where(a%2 ==1 ,0, a**2 ) #(Условие, что, что не удовлетворяет условию, то что удовлетворяет)

array([[ 0,  0,  4],
       [ 0, 16,  0],
       [36,  0, 64]])