<a href="https://colab.research.google.com/github/AlexTapioka/simulative-git/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#Numpy. Урок 1

##Одномерные массивы


Подключение библиотеки

In [169]:
import numpy as np

Создать одномерный массив

In [170]:
a = np.array([1, 2, 3, 4, 5])


Тип массива

In [171]:
type(a)

numpy.ndarray

Число элеменов массива

In [172]:
a.shape

(5,)

Размерность массива

In [173]:
a.ndim

1

Тип элементов массива

In [174]:
a.dtype

dtype('int64')

Установить тип данных при создании массива

In [175]:
arr = [1,2,3,4,5,6,7,8,9,10]
a = np.array(arr, dtype=np.float64)
a.dtype

dtype('float64')

Изменить тип данных в массиве

In [176]:
a.astype(np.int32)
a.dtype

dtype('float64')

Другой способ создать массив

In [177]:
aff = [1,2,3,4,5,6,7,8,9]
b = np.asarray(arr)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###Математичесике операции:


---



Над массивами можно осуществлять различные математические операции( сложение по элементам, вычитание, умножение)

In [178]:
a+b

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [179]:
a-b


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [180]:
a*b

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

Деление одного массива на другой

In [181]:
np.divide(a,b)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

###Аггрегирующие функции:

---



Сумма массива

In [182]:
a.sum()

55.0

Среднее значение массива

In [183]:
a.mean()

5.5

Минимум, максимум

In [184]:
a.min()

1.0

In [185]:
a.max()

10.0

##Многомерные массивы

---



Создание массива

In [18]:
arr2 = [1,2,4,5,6],[1,3,4,5,6]
b = np.array(arr2)
b

array([[1, 2, 4, 5, 6],
       [1, 3, 4, 5, 6]])

Размерность массива (кол - во строк, кол-во столбцов)

In [19]:
b.shape

(2, 5)

Количество размерностей

In [20]:
b.ndim

2

###Математические операции

Сложение (поэлементное сложение)

In [21]:
c = np.array(arr2)
b + c

array([[ 2,  4,  8, 10, 12],
       [ 2,  6,  8, 10, 12]])

###Аггрерирующие функции


Можно применять по размерностям:

axis = 0 (кол-во матриц, из которых состоит массив)

axis = 1 (кол-во строк в каждой матрице)

axis = 2 (кол-во столбцов в каждой матрице)

In [22]:
arr3 = [
    [
    [1, 2, 3, 4, 5, 6],
    [90, 2, 3, 4, 5, 6]
    ],
    [
    [1, 2, 3, 4, 5, 6],
    [9, 2, 3, 4, 5, 6]
    ],
    [
    [1, 2, 3, 4, 5, 6],
    [113, 2, 3, 4, 5, 6]
    ]
    ]
c = np.array(arr3, dtype = np.int32)


In [23]:
c.shape

(3, 2, 6)

In [24]:
c.sum(axis = 0)

array([[  3,   6,   9,  12,  15,  18],
       [212,   6,   9,  12,  15,  18]])

In [25]:
c.sum(axis = 1)

array([[ 91,   4,   6,   8,  10,  12],
       [ 10,   4,   6,   8,  10,  12],
       [114,   4,   6,   8,  10,  12]])

In [26]:
c.sum(axis = 2)

array([[ 21, 110],
       [ 21,  29],
       [ 21, 133]])

In [27]:
c.sum( axis=(0, 1) ) # Сумма всех строк во всех матрицах

array([215,  12,  18,  24,  30,  36])

##Создание матриц


Создать единичную матрицу (с единицами в главной диагонали)

In [28]:
np.eye(5,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

Создать нулевую матрицу (заполненную нулями)

In [29]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [30]:
a = np.empty((2,3,5)) # тоже создает пустую матрицу, но с непредсказуемыми значениями


Создает матрицу, заполненную конкретными значениями

In [31]:
np.full((2,3,5), fill_value=15)

array([[[15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15]],

       [[15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15],
        [15, 15, 15, 15, 15]]])

Создает матрицу, заполненную единицами

In [32]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

Создать матрицу на основе другой, но заполненную единицами

In [33]:
np.ones_like(a)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# Полезные функции

Создать диапазон с дробным шагом


In [34]:
np.arange(0,10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

Создать диапазон с подогнанным под нужное кол-во элементов шагом

In [35]:
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

##Срезы матриц


Правая граница не входит в диапазон


In [36]:
c.shape

(3, 2, 6)

In [37]:
c[1:, :1, 2: ]

array([[[3, 4, 5, 6]],

       [[3, 4, 5, 6]]], dtype=int32)

In [38]:
a = c[0,1]
a

array([90,  2,  3,  4,  5,  6], dtype=int32)

Массив в обратном порядке

In [39]:
a[::-1]

array([ 6,  5,  4,  3,  2, 90], dtype=int32)

Выборка конкретных значений из массива

In [40]:
a[1:4:2] #Каждый второй элемент

array([2, 4], dtype=int32)

Заменить элементы

In [41]:
a[1:4:2] = 100
a

array([ 90, 100,   3, 100,   5,   6], dtype=int32)

Если создаем копию на основе массива, нужно использовать метод copy(). Тогда элементы в исходном массиве не будут изменяться

In [42]:
b = a
b[::3] = 1000
b

array([1000,  100,    3, 1000,    5,    6], dtype=int32)

In [43]:
c = a.copy()
print(c, a)
c[1] = 10000
print(c, a)

[1000  100    3 1000    5    6] [1000  100    3 1000    5    6]
[ 1000 10000     3  1000     5     6] [1000  100    3 1000    5    6]


# Numpy Урок 2


##Броадкастинг

In [66]:
x = np.array([1,2,3,])
a = 5

In [67]:
x * a # (a преобразовывается в массив)

array([ 5, 10, 15])

In [68]:
x = np.ones((2,3,5,1))
y = np.ones((2,1,5,8))

c = x * y #берет большую размерность

c.shape

(2, 3, 5, 8)

In [69]:
x = np.ones((3,5,1))
y = np.ones((2,1,5,8))

z =x * y #Добавляет измерение, если матрицы разной размерности.
          #Если они приводимы.
z.shape

(2, 3, 5, 8)

In [70]:
a = np.ones((3,5,4,1))
a.shape, a.ndim

((3, 5, 4, 1), 4)

Переделать исходный массив в ту форму, которую мы указываем.
Не меняет кол-во данных!!!



In [71]:
a.reshape((3,5,2,2))
a.shape

(3, 5, 4, 1)

Переделать исходный массив в ту форму, которую мы указываем. Меняет кол-во данных.

In [72]:
np.resize(a, (3,5,4,2)) #не меняет исходный массив
                        # недостающие данные заполняются копией данных из исходного массива

a.shape

(3, 5, 4, 1)

In [73]:
b = np.ones((3,5,4,1)) # Меняет исходный массив.
                      # Недостающие данные заполняются 0
b.resize((3,5,4,2))
b.shape

(3, 5, 4, 2)

Расширить массив измерениями с единицами

In [74]:
a = np.ones((2, 255, 255))
b = np.expand_dims(a, axis = (0,2,4)) #в скобках указать оси
b.shape

(1, 2, 1, 255, 1, 255)

Удалить измерения из массива

In [75]:
b.squeeze(axis =(0,2)).shape # по умолчанию удаляет оси с единицами

(2, 255, 1, 255)

Добавить значения по краям массива

In [76]:
np.pad(a, pad_width=(2,3), constant_values=1).shape

(7, 260, 260)

###Сделать массив плоским

Возвращает новый массив с плоской матрицей

In [77]:
b = np.zeros((2, 3, 5, 1))
c = np.ravel(b)
c.shape, b.shape

((30,), (2, 3, 5, 1))

In [78]:
b.flatten() # only as method. return a copy

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
b.reshape(-1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Переделать массив в список python

In [80]:
b.tolist()

[[[[0.0], [0.0], [0.0], [0.0], [0.0]],
  [[0.0], [0.0], [0.0], [0.0], [0.0]],
  [[0.0], [0.0], [0.0], [0.0], [0.0]]],
 [[[0.0], [0.0], [0.0], [0.0], [0.0]],
  [[0.0], [0.0], [0.0], [0.0], [0.0]],
  [[0.0], [0.0], [0.0], [0.0], [0.0]]]]

###Преобразование массивов

1.   Вставка
2.   Разбивка



Разбить массив на отдельные кусочки

In [81]:
a = np.arange(9)

np.split(a, [3,5,15]) # можно указать одно число или индексы или секции

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([], dtype=int64)]

In [82]:
a = np.array([[1,2,3],[1,2,3]])
a.shape

(2, 3)

In [83]:
np.split(a, 3, axis=1)

[array([[1],
        [1]]),
 array([[2],
        [2]]),
 array([[3],
        [3]])]

Вставка в массив

In [84]:
np.insert(a, (1,2), (1000,3000), axis=1)
#куда, на какое место, что вставить, ось

array([[   1, 1000,    2, 3000,    3],
       [   1, 1000,    2, 3000,    3]])

Добавление в конец

In [85]:
np.append(a, values=[[100, 200, 300], [100, 200, 300]], axis =1)
# обязательно соблюдать внешнюю размерность(та, которая не в axis)

array([[  1,   2,   3, 100, 200, 300],
       [  1,   2,   3, 100, 200, 300]])

  ### Поиск уникальных значений в массиве

In [88]:
a = np.array([[1,2,3],[4,5,6]])
a =np.append(a, [[1,2,3]], axis = 0)


In [89]:
a = np.append(a, [[1],[1],[1]], axis = 1)


Сделает массив плоским и оставит уникальные элементы

In [90]:
np.unique(a)

array([1, 2, 3, 4, 5, 6])

Выводит уникальные массивы

In [91]:
np.unique(a, axis=0)

array([[1, 2, 3, 1],
       [4, 5, 6, 1]])

возвращает индексы первого вхождения уникальных значений

In [95]:
els, inxs = np.unique(a, axis=0, return_index=True)
inxs

array([0, 1])

вывести все вхождения уникальных индексов в массив

In [97]:
els, inxs = np.unique(a, axis=0, return_inverse=True)
inxs

array([0, 1, 0])

Это позволит сконструировать исходный массив

In [98]:
els[inxs]

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

Сколько каждый элемент массива повторился

In [100]:
els, cnt = np.unique(a, axis=0, return_counts=True)
cnt

array([2, 1])

###Дублировать массив(значения)

Повторить каждую строку массива, указанное кол-во раз

In [103]:
a

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [102]:
np.tile(a, 2)

array([[1, 2, 3, 1, 1, 2, 3, 1],
       [4, 5, 6, 1, 4, 5, 6, 1],
       [1, 2, 3, 1, 1, 2, 3, 1]])

Повторение строк, но в другом измерении **подряд**

In [104]:
np.tile(a, (2,1))

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1],
       [1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

Плоский массив, в котором значения продублированы указанное кол-во раз

In [105]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 1, 1, 4, 4, 5, 5, 6, 6, 1, 1, 1, 1, 2, 2, 3, 3,
       1, 1])

если указываем ось, просто повторяет ее ее **последовательно**

In [106]:
np.repeat(a, 2, axis=0)

array([[1, 2, 3, 1],
       [1, 2, 3, 1],
       [4, 5, 6, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1],
       [1, 2, 3, 1]])

###Конкантенация и обьединение массивов

Обьединить два массива, по совпадающей размерности.

In [113]:
a

array([[1, 2, 3, 1],
       [4, 5, 6, 1],
       [1, 2, 3, 1]])

In [111]:

b = np.repeat(a, 3, axis=1)
b

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [4, 4, 4, 5, 5, 5, 6, 6, 6, 1, 1, 1],
       [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

In [112]:
np.concatenate((a,b), axis =1)

array([[1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [4, 5, 6, 1, 4, 4, 4, 5, 5, 5, 6, 6, 6, 1, 1, 1],
       [1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

Если размерности совпадают, можно не указывать ось

In [116]:
c = a.copy()
np.concatenate((a,c*2)) #можно умножить значения или что-то другое

array([[ 1,  2,  3,  1],
       [ 4,  5,  6,  1],
       [ 1,  2,  3,  1],
       [ 2,  4,  6,  2],
       [ 8, 10, 12,  2],
       [ 2,  4,  6,  2]])

Горизонтальное соединение по столбцам (ставим одно на другое) или concantenate с axis = 2

In [117]:
np.hstack((a,b))

array([[1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [4, 5, 6, 1, 4, 4, 4, 5, 5, 5, 6, 6, 6, 1, 1, 1],
       [1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

Конкантенация по строкам или concantenate с axis = 0

In [118]:
np.vstack((a,b))

ValueError: ignored

#Полезные функции

Произведение всех элементов по заданному правилу

Произведение всех элементов массива

In [120]:
a.prod()

4320

Осторожно!!! Если массив пустой, получаем 1

In [121]:
np.array([]).prod()

1.0

Умножение по столбикам

In [125]:
a.prod(axis=0)

array([ 4, 20, 54,  1])

Умножение по строкам

In [124]:
a.prod(axis=1)

array([  6, 120,   6])

  Округлить каждый элемент массива до указанного знака после запятой

In [129]:
b = a*1.025467
b
b.round(2)

array([[1.03, 2.05, 3.08, 1.03],
       [4.1 , 5.13, 6.15, 1.03],
       [1.03, 2.05, 3.08, 1.03]])

### Сортировка

Сравает все значения между собой

In [132]:
np.sort(b)

array([[1.025467, 1.025467, 2.050934, 3.076401],
       [1.025467, 4.101868, 5.127335, 6.152802],
       [1.025467, 1.025467, 2.050934, 3.076401]])

Сравнивает массивы между собой

In [ ]:
np.sort(b, axis=0)

выводит индексы элементов ранжированные по значениям

In [133]:
np.argsort(b) #По умлочанию axis=1

array([[0, 3, 1, 2],
       [3, 0, 1, 2],
       [0, 3, 1, 2]])

In [134]:
np.argsort(b, axis=0)

array([[0, 0, 0, 0],
       [2, 2, 2, 1],
       [1, 1, 1, 2]])

Плоский массив

In [135]:
np.argsort(b, axis=None)

array([ 0,  3,  7,  8, 11,  1,  9,  2, 10,  4,  5,  6])

Найти индекс минимального элемента


In [139]:
np.argmin(b)

0

Найти индекс максимального элемента

In [140]:
np.argmax(a)

7

Извлечь диагональ из квадрата матриц (по умолчанию - главная (от верхнего левого элемента к правому нижнему))

In [144]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
np.diag(a)

array([0, 4, 8])

извлечь диагональ по значению k (если k > 0, то это диагональ над главной диагональю (справа),если  k < 0, то это диагональ под главной диагональю(слева))

In [150]:
np.diag(a, k=-2)

array([6])

## Фильтрация

Фильтраця по условию (Получаем 2 массива. 1-строки, 2-столбцы. это положение эл-тов которые удовлетворяют условию)


In [157]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [155]:
np.where(a<3)

(array([0, 0, 0]), array([0, 1, 2]))

In [156]:
np.where(a%2 ==1)

(array([0, 1, 1, 2]), array([1, 0, 2, 1]))

Вернуть результат со значениямы в одномерном массиве

In [158]:
a[np.where(a%2 ==1)]

array([1, 3, 5, 7])

Комбинирование условий

и

In [159]:
np.where((a%2 == 1)&(a > 3))

(array([1, 2]), array([2, 1]))

In [160]:
np.where(np.logical_and(a%2 == 1,a > 3 ))

(array([1, 2]), array([2, 1]))

или

In [162]:
np.where((a%2 == 1)|(a > 3))

(array([0, 1, 1, 1, 2, 2, 2]), array([1, 0, 1, 2, 0, 1, 2]))

In [161]:
np.where(np.logical_or(a%2 == 1,a > 3 ))

(array([0, 1, 1, 1, 2, 2, 2]), array([1, 0, 1, 2, 0, 1, 2]))

Можем менять значение отфильтрованных данных

In [163]:
np.where(a>5, a,-1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [ 6,  7,  8]])

In [168]:
np.where(a%2 ==1 ,0, a**2 ) #(Условие, что, что не удовлетворяет условию, то что удовлетворяет)

array([[ 0,  0,  4],
       [ 0, 16,  0],
       [36,  0, 64]])

#Numpy Урок 3

In [4]:
a = np.array([
    [
        [1, 2, 3],
        [4,10, 7]
    ],
    [
        [101, 13, 28],
        [44, 5, 18]
    ]

])

Найти разницу между максимальным и минимальным значением или размах

In [9]:
a.ptp()

100

Размах по осям

In [10]:
a.ptp(axis = 2)

array([[ 2,  6],
       [88, 39]])

In [11]:
a.ptp(axis = 1)

array([[ 3,  8,  4],
       [57,  8, 10]])

In [12]:
a.ptp(axis =(1,2))

array([ 9, 96])

перцентиль(0%=100%)

In [18]:
np.percentile(a, 50, axis = (1,2), method='closest_observation')

array([ 3, 18])

 квантиль (0-1)

In [19]:
np.quantile(a, 0.5, axis=(1,2), method='closest_observation') # метод помогает считать элементы  без интерполяции (т. е. элементы из исходных массивов)

array([ 3, 18])

медиана

In [20]:
np.median(a, axis=(1,2)) # с интерполяцией

array([ 3.5, 23. ])

среднее значение

In [21]:
np.average(a)

19.666666666666668

In [22]:
np.average(a, axis =1)

array([[ 2.5,  6. ,  5. ],
       [72.5,  9. , 23. ]])

Разброс от среднего (дисперсия)

In [23]:
np.var(a)

748.0555555555553

In [24]:
np.var(a, axis = 1)

array([[  2.25,  16.  ,   4.  ],
       [812.25,  16.  ,  25.  ]])

Стандартное отклонение

In [25]:
np.std(a, axis =(1,2))

array([ 3.09569594, 32.03860519])

расчет коэффициента корреляции Пирсона

In [35]:
x = np.random.rand(3,3)
y = np.random.rand(3,3)

In [28]:
np.corrcoef(x) # для всех эл-тов

array([[ 1.        ,  0.77236112,  0.3239566 ],
       [ 0.77236112,  1.        , -0.35071798],
       [ 0.3239566 , -0.35071798,  1.        ]])

In [31]:
np.corrcoef(x, rowvar=False) # Каждая строчка это переменная. Наблюдения идут по столбцам

array([[ 1.        ,  0.22035972, -0.95137105],
       [ 0.22035972,  1.        ,  0.09083122],
       [-0.95137105,  0.09083122,  1.        ]])

In [32]:
np.corrcoef(x.T) # Транспонированная таблица

array([[ 1.        ,  0.22035972, -0.95137105],
       [ 0.22035972,  1.        ,  0.09083122],
       [-0.95137105,  0.09083122,  1.        ]])

Ковариационная матрица

In [34]:
np.cov(x, rowvar=False)

array([[ 0.03206562,  0.01875524, -0.0308286 ],
       [ 0.01875524,  0.22591291,  0.00781249],
       [-0.0308286 ,  0.00781249,  0.03274674]])

In [36]:
np.cov(x,y)

array([[ 0.10735522, -0.06754134, -0.11728487, -0.02641414, -0.11213227,
        -0.04073749],
       [-0.06754134,  0.17421763,  0.11346791,  0.01147265,  0.19745422,
        -0.09338849],
       [-0.11728487,  0.11346791,  0.14008558,  0.02730729,  0.16073209,
         0.00865365],
       [-0.02641414,  0.01147265,  0.02730729,  0.00670005,  0.02263216,
         0.01467239],
       [-0.11213227,  0.19745422,  0.16073209,  0.02263216,  0.23938821,
        -0.07211523],
       [-0.04073749, -0.09338849,  0.00865365,  0.01467239, -0.07211523,
         0.1229955 ]])

Возвращает совокупную сумму элементов вдоль заданной оси.

In [37]:
np.cumsum(x, ax)

array([0.56887466, 0.86956349, 1.82215112, 2.70301561, 3.09030061,
       3.1413339 , 3.91959846, 4.79134799, 4.9731582 ])

# Глава 5. Загрузка и сохранение данных

Сохранить данные массива в специальный файл

In [40]:
a =np.random.rand(3,5)
a

array([[0.74686761, 0.37998955, 0.44174444, 0.84143027, 0.31392471],
       [0.3734339 , 0.20614919, 0.08177462, 0.20736502, 0.34806352],
       [0.77938731, 0.16691168, 0.31452539, 0.59742767, 0.07803835]])

In [41]:
np.save('Название', a)

Чтение записанного файла



In [43]:
b = np.load('Название.npy')
b

array([[0.74686761, 0.37998955, 0.44174444, 0.84143027, 0.31392471],
       [0.3734339 , 0.20614919, 0.08177462, 0.20736502, 0.34806352],
       [0.77938731, 0.16691168, 0.31452539, 0.59742767, 0.07803835]])

# Глава 6. Линейная алгебра

In [46]:
b

array([[0.65287373, 0.57474506, 0.59540284],
       [0.94650458, 0.65847521, 0.76058442],
       [0.5254275 , 0.8223842 , 0.19114877],
       [0.79981996, 0.42602319, 0.86776124],
       [0.64847855, 0.19496208, 0.00702356]])

Умножение матриц.
Если число столбцов в первой матрице равно числу строк во второй, то такое умножение допустимо.

In [47]:
np.dot(a,b)

array([[1.1724011 , 1.23388589, 0.79951833],
       [1.36121593, 1.03524079, 0.68427472],
       [0.73820778, 0.58093021, 0.34138026]])

In [51]:
np.dot(a,5) #Можно

array([[4.35696239, 0.8942485 , 3.639865  , 0.02879319, 0.36321076],
       [0.63806449, 1.79365491, 2.98952087, 1.24781459, 3.2738138 ],
       [0.30573362, 0.83314679, 1.89242981, 0.59474881, 1.90111076]])

In [49]:
np.matmul(a,b) #не может принимать скалярные значения как аргумент. Ведут себя по разному при умножении многомерных матриц

array([[1.1724011 , 1.23388589, 0.79951833],
       [1.36121593, 1.03524079, 0.68427472],
       [0.73820778, 0.58093021, 0.34138026]])

In [ ]:
np.matmul(a,4) # Так делать нельзя

In [50]:
a@b #то же что и matmul

array([[1.1724011 , 1.23388589, 0.79951833],
       [1.36121593, 1.03524079, 0.68427472],
       [0.73820778, 0.58093021, 0.34138026]])

Перемножить 3 матрицы

In [52]:
np.linalg.multi_dot((a,b,a))

array([[1.22796918, 0.78553991, 1.89382833, 0.40978611, 1.19706285],
       [1.36010455, 0.72884626, 1.8688916 , 0.34759078, 1.03689518],
       [0.73827717, 0.39730988, 1.01394356, 0.18983681, 0.56379681]])

In [53]:
a@b@a

array([[1.22796918, 0.78553991, 1.89382833, 0.40978611, 1.19706285],
       [1.36010455, 0.72884626, 1.8688916 , 0.34759078, 1.03689518],
       [0.73827717, 0.39730988, 1.01394356, 0.18983681, 0.56379681]])

In [54]:
c = np.array([1,2,3])
d = np.array([4,5,6])

скалярные произведения - это сумма попарных произведений `(1*4+2*5+3*6)`

In [55]:
np.inner(c,d)

32

декартовы произведения. внутреннее умножение.каждый элемент первой строки умножается на вторую матрицу

In [57]:
np.outer(c,d)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

След матрицы - сумма всех элементов главной диагонали

In [60]:
np.trace(a)

1.6086094209863133

Определитель матрицы

In [63]:
e = np.random.rand(3,3)
np.linalg.det(e) # матрица должна быть квадратной

0.037588038590807074

Собственные числа

In [65]:
np.linalg.eig(e)

(array([0.85799545+0.j        , 0.0275475 +0.20748559j,
        0.0275475 -0.20748559j]),
 array([[-0.55349342+0.j        , -0.05942689-0.38787166j,
         -0.05942689+0.38787166j],
        [-0.74415315+0.j        ,  0.81782678+0.j        ,
          0.81782678-0.j        ],
        [-0.37400686+0.j        , -0.27236893+0.32093388j,
         -0.27236893-0.32093388j]]))

Матричные уравнения Ax = B

In [66]:
np.linalg.solve(e, c)

array([  5.1906605 , -10.55868257,   5.23378406])

Транспонирование матрицы

In [7]:
a = a.transpose()
a

array([[0.5016054 , 0.68458546, 0.24434123],
       [0.89440966, 0.1949    , 0.82437826],
       [0.37980459, 0.84366653, 0.0919852 ],
       [0.38783285, 0.23394128, 0.40201066],
       [0.43081829, 0.18924368, 0.06671369]])

In [4]:
a.T

array([[0.5016054 , 0.68458546, 0.24434123],
       [0.89440966, 0.1949    , 0.82437826],
       [0.37980459, 0.84366653, 0.0919852 ],
       [0.38783285, 0.23394128, 0.40201066],
       [0.43081829, 0.18924368, 0.06671369]])

#Глава 7: Логические функции



*   np.nan = NOT a NuMBER,
*   np.inf = Infinity
*   np.NINF = Negative infinity



In [13]:
a = np.array([[1,2,3, np.nan, True], [4, np.inf, 5, np.NINF, False]])
a

array([[  1.,   2.,   3.,  nan,   1.],
       [  4.,  inf,   5., -inf,   0.]])

Проверяет можно ли вычислить все эл-ты массива как True

In [14]:
np.all(a)

False

In [16]:
np.all(a, axis=0)

array([ True,  True,  True,  True, False])

In [18]:
np.any(a, axis = 1)

array([ True,  True])

Проверка на конечность

In [19]:
np.isfinite(a)

array([[ True,  True,  True, False,  True],
       [ True, False,  True, False,  True]])

Проверка на бесконечность

In [20]:
np.isinf(a)

array([[False, False, False, False, False],
       [False,  True, False,  True, False]])

Проверка на nan (отсутствие значения)

In [21]:
np.isnan(a)

array([[False, False, False,  True, False],
       [False, False, False, False, False]])

In [24]:
c = np.ones_like(a)


Записать в единичный массив c результат проверки на наличие nan в a

In [26]:
np.isnan(a,out = c) # out не обязательно

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

###Сравнение близости элементов

Сравнить насколько элементы близки

In [31]:
d = np.array([0.0000005, 0.0000006, 0.0000007])
e = d * 1e-6

np.isclose(e, d, atol=1e-7) #значение максимальной разницы между величинами

array([False, False, False])

In [32]:
np.allclose(e, d, atol=1*e-7)

False

Сравнить массивы

In [35]:
a
b = a.copy() # non != non
a == b

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [37]:
np.array_equal(a,b, equal_nan = True)

True

In [38]:
np.equal(a,b)

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

поэлеменнтное сравнение массивов

<=

In [40]:
np.less_equal(a,b)

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

<

In [41]:
np.less(a,b)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

\>=

In [43]:
np.greater_equal(a,b)

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

#Глава 8: Случайные величины

Сгенерировать случайную выборку из раданного массива путем выбора элементов в произвольном порядке

In [11]:
a = [1, 2, 3, 4, 5, 6, 7]

In [5]:
np.random.choice(a, size = (2, 3, 5))

array([[[4, 4, 3, 3, 2],
        [3, 2, 3, 3, 3],
        [4, 6, 4, 3, 5]],

       [[6, 4, 1, 2, 1],
        [1, 4, 2, 2, 3],
        [4, 5, 5, 2, 6]]])

Если указать вместо массива число. То массив генерируется самостоятельно. Правая граница не включается

In [6]:
np.random.choice(a = 10, size = (2, 3, 5))

array([[[7, 2, 0, 3, 3],
        [2, 8, 4, 1, 3],
        [4, 1, 7, 3, 4]],

       [[3, 1, 5, 7, 9],
        [7, 5, 4, 7, 9],
        [2, 1, 0, 6, 0]]])

replace можно ли дублировать элементы из массива

In [8]:
np.random.choice(a = 100, size = (2, 3, 5), replace = False )

array([[[30, 95, 42, 68, 97],
        [86, 23, 17, 76, 78],
        [54, 26, 44, 46, 25]],

       [[24, 70,  5, 20,  1],
        [87, 67, 64, 53, 28],
        [59, 92, 55, 33, 62]]])

p вектор вероятностей. с какой вероятностью нужно брать соответствующте числа из массива a

In [17]:
p = [0, 0, 0, 0, 0, 0.9, 0.1]
np.random.choice(a = a, size = 5, p = p )

array([6, 6, 6, 6, 7])

Перемешать элементы массива. Исходное значение меняется

In [21]:
b = np.array([1,2,3,4,5])
np.random.shuffle(b)
b

array([4, 5, 1, 3, 2])

Перемешивает элементы. Не меняет исходный массив

In [22]:
np.random.permutation(b)

array([2, 1, 4, 5, 3])

Можно вместо массива указать число, тогда он сгенерируется автоматически

In [25]:
np.random.permutation(10)

array([1, 5, 8, 9, 0, 2, 4, 3, 6, 7])

Сгенерировать случайную выборку от 0 до 1

In [26]:
np.random.sample()

0.5620219295991512

Случайный массив заданной формы от 0 до 1. Принимает на вход кортеж

In [27]:
np.random.sample((2,3,5))

array([[[0.84921523, 0.22801915, 0.34975597, 0.94622442, 0.65068964],
        [0.95610471, 0.87443652, 0.55279785, 0.1183903 , 0.1192885 ],
        [0.03607517, 0.78751111, 0.97654007, 0.93292095, 0.17309282]],

       [[0.51879441, 0.20525489, 0.58013341, 0.16476616, 0.59459703],
        [0.16696008, 0.66149276, 0.04138799, 0.66377405, 0.57982892],
        [0.13255782, 0.7351018 , 0.10193602, 0.49302753, 0.30298978]]])

Сгенерировать рандомные числа от 0 до 1. Но принимает на вход числа а не кортеж




In [28]:
  np.random.rand(1,3, 5)

array([[[0.0431885 , 0.73859942, 0.42463433, 0.80763732, 0.14793684],
        [0.22258046, 0.64852752, 0.80438595, 0.82346398, 0.47526218],
        [0.5963797 , 0.77725973, 0.89970895, 0.04881019, 0.03820925]]])

сгенерировать рандомные числа в заданном диапазоне. заданного размера

In [29]:
np.random.randint(5, 10, size = 10)

array([9, 6, 9, 6, 9, 6, 7, 8, 8, 7])

Сгенерировать нормальное (гауссовское) распределение. Первый аргумент - мат ожидание, второй - дисперсия, третий - кол-во чисел

In [32]:
np.random.normal(5, 2.5 , 10)

array([ 3.7701825 , -0.31847022,  4.27196883,  7.32544188,  0.10522893,
        9.47502303,  6.98316329,  6.03775566,  4.87008364,  2.49296971])

Сгенерировать равномерное распределение (первый аргумент-начало диапазона, второй - конец диапазона, третий - кол-во чисел)

In [35]:
np.random.uniform(4, 10 , 10)

array([7.65713031, 8.63245943, 5.18421637, 7.2873166 , 6.76089384,
       7.66443984, 9.61646355, 8.12402726, 8.22229329, 8.21773416])

# Глава 9 Практический кейс

**!!!Чтобы данные отображались корректно!!!**

In [5]:
float_formatter = '{:.2f}'.format
np.set_printoptions(formatter = {'float_kind': float_formatter})

Загрузить данные из текстового файла

In [6]:
data = np.genfromtxt('/content/data.csv', delimiter=',', skip_header=True)

data.shape

(89560, 15)

Средняя скорость поездки

In [48]:
speed_arr = data[:, 7]/(data[:, 8]/3600)
speed_arr.mean()

32.24258580925573

кол-во поездок в феврале

In [52]:
data[data[:, 1] == 2].shape[0]

13333

Ко-во поездок с чаевыми более 50 долларов

In [55]:
data[data[:, -3] > 50].shape[0]

16

In [62]:
data[~np.isnan(np.where(data[:, -3] > 50, data[:, -3], np.nan))].shape[0]

16

Оценка взаимосвязи между переменными

In [8]:
np.cov(data, rowvar=False)

array([[0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
        0.00, 0.00, 0.00, 0.00],
       [0.00, 2.86, -0.11, -0.03, -0.03, 0.02, -0.01, -0.04, 203.37,
        0.44, 0.09, 0.03, -0.06, 0.51, 0.01],
       [0.00, -0.11, 75.59, -0.15, -0.05, 0.05, -0.02, -0.16, 259.87,
        0.29, 0.00, 0.09, -0.20, 0.18, 0.03],
       [0.00, -0.03, -0.15, 4.01, 0.17, 0.00, -0.08, 0.34, -108.82, 0.37,
        -0.25, -0.22, -0.30, -0.40, 0.03],
       [0.00, -0.03, -0.05, 0.17, 1.97, -0.22, 0.16, -0.08, -15.72,
        -0.40, 0.35, -0.25, -0.09, -0.40, 0.01],
       [0.00, 0.02, 0.05, 0.00, -0.22, 0.68, -0.28, -0.95, -83.91, -2.12,
        -0.06, 0.52, 0.24, -1.42, -0.05],
       [0.00, -0.01, -0.02, -0.08, 0.16, -0.28, 1.91, -1.66, -217.96,
        -4.83, 0.00, 0.23, -0.67, -5.27, 0.03],
       [0.00, -0.04, -0.16, 0.34, -0.08, -0.95, -1.66, 26.71, 3413.20,
        58.19, 0.54, 2.80, 6.67, 68.19, -0.11],
       [0.00, 203.37, 259.87, -108.82, -15.72, -83.91, -217.96, 3413.20,
  

In [11]:
np.cov(data[:,[7,8,-2, -3]].T)

array([[26.71, 3413.20, 68.19, 6.67],
       [3413.20, 10489667.24, 11345.40, 924.20],
       [68.19, 11345.40, 269.92, 45.80],
       [6.67, 924.20, 45.80, 23.35]])